## Gaussian Elimination and Gauss-Seiddel 

We will use the naieve Gauss method first to find solutions. The warm-up will have us find solutions to the following system, written in matrix form:
$$\begin{bmatrix} 3 & -2 & 2 \\ 2 & 3 & 14 \\ 3 & 3 & 5\end{bmatrix} \left[ \begin{array}{c} x_1 \\ x_2 \\x_3 \end{array} \right] = \left[ \begin{array}{c} 3 \\ 1 \\ 8 \end{array} \right]$$


In [7]:
#import numpy we don't need any plotting for this
import numpy as np
##declare some variables
#define a matrix
a = np.array([[3,-2,2,3],[2,3,14,1],[3,3,5,8]], dtype=float)
#get rows and columns
rows = np.shape(a)[0]
cols = np.shape(a)[1]
#solution vector to store solutions
x = np.zeros(cols-1)
#print matrix here
print(a)
#forward elimination algorithm here
for i in range(cols - 1):
    #do swaps here
    for j in range(i+1, rows):
        a[j,:] = (-a[j,i]/a[i,i])*a[i,:] + a[j,:]     
#print matrix again in row echelon form
print(a)
#backsubstitution algorithm here
for i in np.arange(rows-1, -1, -1):
    x[i] = (a[i,-1] - a[i,0:cols-1] @x)/a[i,i]
#print solution vector
print(x)
#check the solution
B = np.array([[3,-2,2],[2,3,14],[3,3,5]], dtype=float)
print(B @ x)

[[ 3. -2.  2.  3.]
 [ 2.  3. 14.  1.]
 [ 3.  3.  5.  8.]]
[[  3.          -2.           2.           3.        ]
 [  0.           4.33333333  12.66666667  -1.        ]
 [  0.           0.         -11.61538462   6.15384615]]
[ 2.23178808  1.31788079 -0.52980132]
[3. 1. 8.]


In [8]:
x = 2
y = 1

xPrev = 2
yPrev = 1

m=5
tol = 0.5 * 10 ** (2-m)
maxIt = 50

for i in range(maxIt):
    x = (17 - 3*y)/8
    e1 = (abs(xPrev - x)/abs(x)) * 100
    y = (7 - x)/2
    e2 = (abs(yPrev - y)/abs(y)) * 100
    maxError = max(e1, e2)
    print("It. Num:",i,"x:",x,"y:",y,"Max Rel. Error:", maxError,"%")
    if maxError < tol:
        break
    xPrev = x
    yPrev = y

It. Num: 0 x: 1.75 y: 2.625 Max Rel. Error: 61.904761904761905 %
It. Num: 1 x: 1.140625 y: 2.9296875 Max Rel. Error: 53.42465753424658 %
It. Num: 2 x: 1.0263671875 y: 2.98681640625 Max Rel. Error: 11.132254995242626 %
It. Num: 3 x: 1.00494384765625 y: 2.997528076171875 Max Rel. Error: 2.131794716064379 %
It. Num: 4 x: 1.0009269714355469 y: 2.9995365142822266 Max Rel. Error: 0.401315613959533 %
It. Num: 5 x: 1.000173807144165 y: 2.9999130964279175 Max Rel. Error: 0.07530334087955923 %
It. Num: 6 x: 1.000032588839531 y: 2.9999837055802345 Max Rel. Error: 0.014121370264339923 %
It. Num: 7 x: 1.000006110407412 y: 2.999996944796294 Max Rel. Error: 0.002647827032587341 %
It. Num: 8 x: 1.0000011457013898 y: 2.999999427149305 Max Rel. Error: 0.0004964700334228303 %


1.  Modify your code to compute the determinant for the following matrix using elimination. You will need to ensure that it goes through all the rows and columns instead of leaving the last column, as it does in the example code.
$$ \begin{bmatrix}
1 & 3 & 4 & 6 & 3 \\
2 & 2 & 3 & 7 & 12 \\
9 & 2 & 3 & 5 & 8 \\ 
11 & 4 & 9 & 1 & 2 \\
2 & 4 & 2 & 1 & 6
\end{bmatrix}$$

In [60]:
import numpy as np

a = np.array([[1,3,4,6,3],
              [2,2,3,7,12],
              [9,2,3,5,8],
              [11,4,9,1,2],
              [2,4,2,1,6]], dtype=float)

rows = np.shape(a)[0]
cols = np.shape(a)[1]

print(a)

for i in range(cols - 1):
    for j in range(i+1, rows):
        a[j,:] = (-a[j,i]/a[i,i])*a[i,:] + a[j,:]   
        
print("updated matrix:")
print(a)

determinant = a[0][0] * a[1][1] * a[2][2] * a[3][3] * a[4][4]

print("determinant:", determinant)


[[ 1.  3.  4.  6.  3.]
 [ 2.  2.  3.  7. 12.]
 [ 9.  2.  3.  5.  8.]
 [11.  4.  9.  1.  2.]
 [ 2.  4.  2.  1.  6.]]
updated matrix:
[[   1.            3.            4.            6.            3.        ]
 [   0.           -4.           -5.           -5.            6.        ]
 [   0.            0.           -1.75        -17.75        -56.5       ]
 [   0.            0.            0.          -41.42857143 -114.85714286]
 [   0.            0.            0.            0.           35.14482759]]
determinant: -10192.000000000002


2.  Use the Gauss-Seidel method to solve the following system:
$$\begin{bmatrix} 12 & 3 & 5 \\ 3 & 8 & 1 \\ 1 & 4 & 10\end{bmatrix} \left[ \begin{array}{c} x_1 \\ x_2 \\x_3 \end{array} \right] = \left[ \begin{array}{c} 2 \\ 2 \\ 3 \end{array} \right] $$ with initial guess $ x=\left[1 1 1 \right]^T$. Set your max relative error so that you guarantee at least 8 significant digits in all your final answers.

In [3]:
##2
x = 1
y = 1
z = 1

xPrev = 1
yPrev = 1
zPrev = 1

m=8
tol = 0.5 * 10 ** (2-m)
maxIt = 50

for i in range(maxIt):
    x = 1/12*(2-3*y-5*z)
    e1 = (abs(xPrev - x)/abs(x)) * 100
    y = 1/8*(2 - z - 3*x)
    e2 = (abs(yPrev - y)/abs(y)) * 100
    z = 1/10*(3 - 4*y - x)
    e3 = (abs(zPrev - z)/abs(z)) * 100
    maxError = max(e1, e2, e3)
    print("It. Num:",i,"x:",x,"y:",y,"z:",z,"Max Rel. Error:", maxError)
    if maxError < tol:
        break
    xPrev = x
    yPrev = y
    zPrev = z

It. Num: 0 x: -0.5 y: 0.3125 z: 0.225 Max Rel. Error: 344.44444444444446
It. Num: 1 x: -0.005208333333333333 y: 0.223828125 z: 0.21098958333333334 Max Rel. Error: 9500.000000000002
It. Num: 2 x: 0.022797309027777785 y: 0.21507731119791668 z: 0.21168934461805555 Max Rel. Error: 122.84626368396002
It. Num: 3 x: 0.02469344527633101 y: 0.21427878994411892 z: 0.2118191394947193 Max Rel. Error: 7.678702697556333
It. Num: 4 x: 0.02483899439117056 y: 0.21420798466647112 z: 0.21183290669429453 Max Rel. Error: 0.5859702391626902
It. Num: 5 x: 0.02485095937742617 y: 0.21420177689667835 z: 0.21183419330358602 Max Rel. Error: 0.04814697925294898
It. Num: 6 x: 0.024851975232669576 y: 0.21420123512480066 z: 0.2118343084268128 Max Rel. Error: 0.0040876237558452825
It. Num: 7 x: 0.024852062707627832 y: 0.21420118793128795 z: 0.21183431855672208 Max Rel. Error: 0.000351982687655191
It. Num: 8 x: 0.024852070285210488 y: 0.21420118382345582 z: 0.2118343194420966 Max Rel. Error: 3.049075013927061e-05
It. N

3. Use the Gauss-Seidel Method with the system from number 2, but with the rows in a different order. Do not change order of your matrix.
$$\begin{bmatrix} 3 & 8 & 1 \\ 12 & 3 & 5 \\ 1 & 4 & 10\end{bmatrix} \left[ \begin{array}{c} x_1 \\ x_2 \\x_3 \end{array} \right] = \left[ \begin{array}{c} 2 \\ 2 \\ 3 \end{array} \right] $$
Use the same initial guess as in number 2. Track the maximum absolute relative error you are getting. What do you notice is happening? Explain why there is a difference between the two solutions.

In [5]:
##3
#the max abs rel. error decreases with a lower interval (takes longer to decrease), and it takes longer for the values to converge, but the ending
#max rel. error is slghtly higher than the previous question. switching the order affects the solutions/error.
#there is a difference since switching the rows will make the updated variable change since we switched the order of the 
#first two rows. the variable we plug into the 2nd row was previously the first row, and vice versa. 
#this not only affects the iteration num but also the final values (which it slightly made the 1st row solution converge closer, but the 3rd one is further away)

x = 1
y = 1
z = 1

xPrev = 1
yPrev = 1
zPrev = 1

m=8
tol = 0.5 * 10 ** (2-m)
maxIt = 50

for i in range(maxIt):
    x = 1/8*(2 - z - 3*x)
    e1 = (abs(xPrev - x)/abs(x)) * 100
    y = 1/12*(2-3*y-5*z) 
    e2 = (abs(yPrev - y)/abs(y)) * 100
    z = 1/10*(3 - 4*y - x)
    e3 = (abs(zPrev - z)/abs(z)) * 100
    maxError = max(e1, e2, e3)
    print("It. Num:",i,"x:",x,"y:",y,"z:",z,"Max Rel. Error:", maxError,"%")
    if maxError < tol:
        break
    xPrev = x
    yPrev = y
    zPrev = z

It. Num: 0 x: -0.25 y: -0.5 z: 0.525 Max Rel. Error: 500.0 %
It. Num: 1 x: 0.278125 y: 0.07291666666666666 z: 0.24302083333333335 Max Rel. Error: 785.7142857142858 %
It. Num: 2 x: 0.1153255208333333 y: 0.04717881944444442 z: 0.2695959201388889 Max Rel. Error: 141.16518008354979 %
It. Num: 3 x: 0.1730534396701389 y: 0.04254032841435185 z: 0.2656785246672454 Max Rel. Error: 33.358434797275386 %
It. Num: 4 x: 0.15189514454029224 y: 0.045332199285059785 z: 0.26667760583194683 Max Rel. Error: 13.929540140260462 %
It. Num: 5 x: 0.15970462006839706 y: 0.0442179477487572 z: 0.2663423588936574 Max Rel. Error: 4.889949661293605 %
It. Num: 6 x: 0.15681797261264394 y: 0.044636196857120114 z: 0.2664637239958876 Max Rel. Error: 1.8407631521186858 %
It. Num: 7 x: 0.15788529477077257 y: 0.04448106578743347 z: 0.2664190442079494 Max Rel. Error: 0.6760111254681658 %
It. Num: 8 x: 0.15749063393496662 y: 0.04453846513316273 z: 0.26643555055323825 Max Rel. Error: 0.2505932104946079 %
It. Num: 9 x: 0.157636